version: "3.1"
services:
  redis:
    image: redis:alpine
    container_name: laravel-redis

  mysqldb:
    image: mysql:5.6
    container_name: laravel-mysql
    working_dir: /application
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=banco
      - MYSQL_USER=user
      - MYSQL_PASSWORD=senha
    ports:
      - "3306:3306"

  webserver:
    image: nginx:alpine
    container_name: laravel-webserver
    working_dir: /application
    volumes:
      - ./:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  php-fpm:
    build: phpdocker/php-fpm
    container_name: laravel-php-fpm
    working_dir: /application
    volumes:
      - ./app:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysqldb
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
